@startuml
hide empty members
hide empty methods

package Investigation {

    class CriminalOffence {
    }

    class PoliceInvestigation {
    }

    class PreChargeDecision {
    }

    class Suspect {
    }

}

class CriminalCase {
}

class PNCId {
}

class PublicProsecutionService {
}

Suspect *-- "*" CriminalOffence

PoliceInvestigation *-- "*" Suspect

PoliceInvestigation *-- "*" PNCId

@enduml
