@startuml
hide empty members
hide empty methods

package Investigation {

    class CriminalOffence {
    }

    class PoliceInvestigation {
    }

    class PreChargeDecisionCase {
    }

    class Suspect {
    }

}

package Preparation {
    class CriminalCase {
    }

    class Defendant {
    }

    class PoliceCaseFile {
    }
}

class PNCId {
}

class PublicProsecutionService {
    PreChargeDecisionCase ReceiveRequestForPreChargeDecision (PoliceInvestigation)
    CriminalCase AcceptCaseFile (PoliceCaseFile)
}

Suspect *-- "*" CriminalOffence

PoliceCaseFile *-- PNCId

PoliceCaseFile *-- Defendant

PoliceInvestigation *-- "*" Suspect

PoliceInvestigation *-- "*" PNCId

PreChargeDecisionCase *-- "*" Suspect

PreChargeDecisionCase *-- "*" OffenceAdvice

CriminalCase *-- "*" Defendant

@enduml
